config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :posts, only: [:new, :create, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 64 }
  validates :content, presence: true, length: { maximum: 1024 }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :posts
  before_create :remember
  has_secure_password

  def remember
    remember_token = SecureRandom.urlsafe_base64
    self.remember_digest = Digest::SHA1.hexdigest(remember_token)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def digest(token)
    Digest::SHA1.hexdigest(token)
  end

  def sign_in(user)
    remember_token = SecureRandom.urlsafe_base64
    remember_digest = digest(remember_token)
    user.update_attribute(:remember_digest, remember_digest)
    cookies.permanent[:remember_token] = remember_token
    current_user
  end

  def current_user
    if cookies.permanent[:remember_token]
      remember_token = cookies.permanent[:remember_token]
      @current_user ||= User.find_by(remember_digest: digest(remember_token))
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def sign_out(user)
    user.update_attribute(:remember_digest, nil)
    cookies.delete :remember_token
  end

  def logged_in?(user)
    
    !!@current_user
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :make_posts, only: [:new,:create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(user_id: @current_user.id, title: params[:post][:title],
                     content: params[:post][:content])
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  private

  def make_posts
    current_user
    unless logged_in?(@current_user)
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def home
  end

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in(@user)
      flash[:success] = "Welcome #{@user.name}!"
      redirect_to root_path
    end

  end

  def destroy
    @user = current_user
    sign_out(@user) if @user
    flash[:success] = "You signed out"
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Members Only </title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<li>
  <%= post.title %>
  <br>
  <%= post.content %>
  <% if cookies[:remember_token] %>
    <br>
    <p>Posted by: <%= post.user.name %></p>
  <% end %>
</li>
<br>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<% provide(:title, 'Forum') %>
<h1>Forum</h1>

<ul class="posts">
  <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>
<h1>New Post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:post, url: posts_path) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", '#' %></p>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Welcome to the Members Only App</h1>
<% if !!cookies[:remember_token] %>
  <p>Welcome <%= @user.name %></p>
  <%= link_to 'Sign Out', logout_path, method: :delete %>
  <%= link_to 'Post', new_post_path %>
<% else %>
  <%= link_to 'Log In',login_path  %>
<% end %>
<%= link_to 'Forum', posts_path %>